### ISSUE TITLE
Add prettier configuration file

### ISSUE THREAD

**Issue by fredoist** [midudev/miduconf-website#19]
Cuando no existe un archivo de configuración para prettier, este utiliza la configuración global definida por el usuario en su editor de código, lo que causa que exista inconsistencias en el formato al momento de correr el comando `npm run format`.

Agregué un archivo de configuración para prettier que mantenga la misma consistencia en todo el código.

**Comment by midudev** [comment]
:D Pero la PR no la veo, no?
