### ISSUE TITLE
El botón "Inicio" no funciona cuando estamos en "Código de Conducta"

### ISSUE THREAD

**Issue by hbiblia** [midudev/miduconf-website#24]
Hola, saludo

Cuando estoy en la sección o página "Código de conducta" el botón de inicio no me envía a la página principal.

https://user-images.githubusercontent.com/1939353/179863269-ed6a6234-b13f-49db-a9f7-7b2a419f7d06.mp4

**Comment by midudev** [comment]
Fixed!
