### ISSUE TITLE
El enlace que lleva a google calendar no añade el evento.

### ISSUE THREAD

**Issue by torresgol10** [midudev/miduconf-website#27]
Al hacer click en el enlace que lleva a Google Calendar no añade el evento y salta el siguiente error en Google Calendar "No se ha podido encontrar el evento solicitado", entiendo que el evento generado no esta publico o se ha borrado, adjunto captura de pantalla para que sepas donde esta el enlace (cuadrado rojo). 

![miduconf com_](https://user-images.githubusercontent.com/40922354/180672959-f43f53c1-b603-4bec-85c1-6c3450e16aef.png)

**Comment by d3vcloud** [comment]
Me parece que esta issue ya está solucionada 🙂.
