### ISSUE TITLE
La página no se ve correctamente en móviles 

### ISSUE THREAD

**Issue by ssaavedraa** [midudev/miduconf-website#30]
La página del ticket se ve cortada en dispositivos móviles ![Screenshot_20220730_150523_com.android.chrome.jpg](https://user-images.githubusercontent.com/66895659/182001893-719d22e4-cd60-4c0c-825d-147d07ccc853.jpg)

**Comment by d3vcloud** [comment]
Hola 😄, el modo responsivo será implementado próximamente, es más, ya hay una PR con esta feature que tiene buena pinta.

**Comment by midudev** [comment]
Creo que ya está arreglado esto!
