### ISSUE TITLE
No se ven los patrocinadores en el readme

### ISSUE THREAD

**Issue by edgarguitarist** [midudev/miduconf-website#36]
<img width="323" alt="image" src="https://user-images.githubusercontent.com/47311955/182167663-8e7d22d9-42a6-44c1-9989-bbd74a3193db.png">

Los patrocinadores son una parte esencial del proyecto ya que hacen posible todo esto... necesitamos que se vea, por alguna razón no se ven los svg, no se ha modificado ni cambiado nada en la carpeta de los assets donde se encuentran, pero no son visibles por el momento.

**Comment by ediaz2** [comment]
Borraron los namespaces de los svg `xmlns="http://www.w3.org/2000/svg"`, al ser usando como imagenes en una etiqueda `<img>` es necesario para que se muestre correctamente, si se usa dentro el html no es necesario, como se esta usando en los demas componentes.

Encontre el commit 
https://github.com/midudev/miduconf-website/commit/540fa2e1f592487f14ea20ee810348eb46ddd41d#diff-d9e6a1fcc468e19dd0baa6fe0aa5ea3ff567d1083916ac091b46d0b6c001c60e

**Comment by Pixelao** [comment]
Fixed on PR #52 👍
