### ISSUE TITLE
[Mobile] No se ven los flavours para cambiar el diseño del ticket

### ISSUE THREAD

**Issue by jelowin** [midudev/miduconf-website#41]
En mi dispositivo Iphone XR no puedo ver los iconos para cambiar de flavour mi ticket.

![0DEEB005-2E95-41C9-851E-275678C7262D](https://user-images.githubusercontent.com/74491547/182391390-926c68e9-29d7-4bc5-90eb-f7a1dc1c1206.png)

**Comment by d3vcloud** [comment]
@jelowin aún persiste la issue?

**Comment by midudev** [comment]
Arreglado! Ya deberían verse!

**Comment by jelowin** [comment]
Si, está arreglado! 👏
Porque no se veian?
