### ISSUE TITLE
Logo php es muy grande

### ISSUE THREAD

**Issue by GuauDev** [midudev/miduconf-website#94]
El logo php es demasiado grande que no deja clicarle en el de vite

![image](https://github.com/midudev/miduconf-website/assets/122684235/4ced3206-3fdd-4bc7-8e5e-26025d547a64)

**Comment by GuauDev** [comment]
El logo de typescript tambien es muy grande

![image](https://github.com/midudev/miduconf-website/assets/122684235/6784f30f-70e3-423d-9be0-934d7ed15022)

**Comment by FabianMontoya** [comment]
Lo del logo de PHP lo estoy resolviendo con este PR #111 y si vi que tienes azón, el logo de TS y el de JS tienen el SVG mal

**Comment by FabianMontoya** [comment]
#114
