### ISSUE TITLE
La fecha se superpone al título del Ticket 

### ISSUE THREAD

**Issue by arch-fan** [midudev/miduconf-website#96]
![captura](https://github.com/midudev/miduconf-website/assets/55891793/8dc2c11e-220a-4ab8-b79c-e11ac5df46e0)

Iba a hacer un PR, pero es un cambio sustancial de diseño.

**Comment by arch-fan** [comment]
Y el link de twitch se queda por debajo también

**Comment by FabianMontoya** [comment]
Lo estan intentando arreglar en el PR #112
